version: "3.8"
services:
  app:
    image: 'total-score:latest'
    build:
      context: .
    container_name: total-score
    ports:
      - "8081:8085"
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/total_score_db
      - DB_USERNAME=total_score_user
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    restart: on-failure
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: total_score_user
      POSTGRES_PASSWORD: Zxcvbn123
      POSTGRES_DB: total_score_db
networks:
  db:
    driver: bridge

volumes:
  postgres-data: